import openpyxl
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()

# Column headers
headers = [
    "Serial No.", "Article Title", "First Author", "Year", "Journal Source",
    "Publisher", "Country", "Institution/State", "Dairy Animal Type/Breed",
    "Sample Size", "NAAS Rating", "Journal Impact Factor",
    "Journal Verification Status", "DOI/Article Link", "Direct PDF Link",
    "AIM/OBJECTIVES OF STUDY", "Research Gap", "Biopolymer Type",
    "P4 Sponge/Device Type", "Hormones Used", "Methodology",
    "Day-wise Protocol", "Timing Relative to AI/Mating",
    "Estrus Induction Rate (%)", "Conception Rate (%)", "Pregnancy Rate (%)",
    "Key Findings", "Major Results", "Statistical Significance",
    "Advantages of Biopolymer-Based System", "Limitations", "Notes"
]


# ============================================================
# SHEET 1: INDIA STUDIES
# ============================================================
india_studies = [
    {
        "sno": 1,
        "title": "Plasma progesterone profile and conception rate following exogenous supplementation of gonadotropin-releasing hormone, human chorionic gonadotropin, and progesterone releasing intra-vaginal device in repeat-breeder crossbred cows",
        "author": "Pandey NKJ",
        "year": 2016,
        "journal": "Veterinary World",
        "publisher": "Veterinary World (Open Access)",
        "country": "India",
        "institution": "College of Veterinary & Animal Sciences, GBPUAT, Pantnagar, Uttarakhand",
        "animal": "Crossbred repeat breeder cows",
        "sample": "18 (3 groups x 6)",
        "naas": "6.84",
        "impact": "2.3",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; NAAS listed",
        "doi": "https://doi.org/10.14202/vetworld.2016.559-562",
        "pdf": "https://www.veterinaryworld.org/Vol.9/June-2016/2.pdf",
        "aim": "To evaluate conception rate and plasma P4 profile following GnRH, hCG, and P4-releasing intravaginal device (PRID) supplementation in repeat breeder crossbred cows",
        "gap": "Limited data on comparative efficacy of GnRH vs hCG vs PRID for improving luteal support in repeat breeders under Indian conditions",
        "biopolymer": "Silicone matrix (PRID - standard polymer-impregnated P4 device)",
        "device": "PRID (Progesterone Releasing Intravaginal Device, 1.55 g P4)",
        "hormones": "Progesterone (PRID), GnRH, hCG",
        "methodology": "Repeat breeder cows divided into 3 groups: T1-GnRH on Day 5 post-AI; T2-hCG on Day 5 post-AI; T3-PRID insertion Day 5-19 post-AI. Plasma P4 measured on Day 0, 4, 8 of treatment and Day 18 post-AI.",
        "protocol": "Day 0 → AI\nDay 5 → PRID inserted (T3 group)\nDay 19 → PRID removed\nDay 45 → Pregnancy diagnosis",
        "timing": "PRID inserted Day 5 post-AI for luteal support",
        "estrus_rate": "Not Reported",
        "conception": "66.66 (T3-PRID group)",
        "pregnancy": "Not Reported",
        "findings": "PRID group showed highest conception rate (66.66%) compared to GnRH (50%) and hCG (33.33%). P4 levels were significantly higher in PRID group on Day 8 and Day 18 post-AI.",
        "results": "Conception rate: T1(GnRH)=50%, T2(hCG)=33.33%, T3(PRID)=66.66%. Plasma P4 on Day 18 post-AI significantly higher in T1 than T2 and T3.",
        "stats": "P<0.05 for plasma P4 differences between groups",
        "advantages": "Non-invasive sustained P4 release; improved luteal support; easy insertion/removal",
        "limitations": "Small sample size; single location study",
        "notes": "PMID: 27397976; PMC4937044"
    },
    {
        "sno": 2,
        "title": "Comparison of ovsynch and progesterone-based protocol for induction of synchronized ovulation and conception rate in subestrous buffalo during low-breeding season",
        "author": "Kumar PR",
        "year": 2015,
        "journal": "Veterinary World",
        "publisher": "Veterinary World (Open Access)",
        "country": "India",
        "institution": "NTR College of Veterinary Science, Gannavaram, Andhra Pradesh",
        "animal": "Subestrous Murrah buffalo",
        "sample": "19",
        "naas": "6.84",
        "impact": "2.3",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; NAAS listed",
        "doi": "https://doi.org/10.14202/vetworld.2015.255-259",
        "pdf": "https://www.veterinaryworld.org/Vol.8/March-2015/2.pdf",
        "aim": "To compare ovsynch and CIDR-based progesterone protocol for synchronized ovulation and conception in subestrous buffalo during low-breeding season",
        "gap": "Limited studies on CIDR-based protocols in subestrous buffalo under tropical heat stress conditions",
        "biopolymer": "Silicone elastomer (CIDR matrix)",
        "device": "CIDR (Controlled Internal Drug Release, 1.38 g P4)",
        "hormones": "Progesterone (CIDR), GnRH, PGF2α, Estradiol benzoate",
        "methodology": "Buffalo divided into Ovsynch (n=10) and CIDR+Ovsynch (n=9) groups. CIDR inserted for 9 days with GnRH on Day 0, PGF2α on Day 7, CIDR removal Day 9, EB on Day 10, FTAI on Day 11.",
        "protocol": "Day 0 → GnRH + CIDR insertion\nDay 7 → PGF2α injection\nDay 9 → CIDR removal\nDay 10 → Estradiol benzoate\nDay 11 → Fixed-time AI",
        "timing": "FTAI 24 h after estradiol benzoate injection",
        "estrus_rate": "100 (CIDR group)",
        "conception": "44.44 (CIDR group)",
        "pregnancy": "Not Reported",
        "findings": "CIDR-based protocol induced 100% estrus vs 80% in Ovsynch group. Higher conception rate in CIDR group (44.44%) vs Ovsynch (30%).",
        "results": "Estrus induction: CIDR=100%, Ovsynch=80%. Conception: CIDR=44.44%, Ovsynch=30%. Ovulation rate: CIDR=88.89%, Ovsynch=70%.",
        "stats": "P<0.05 for follicle size differences; conception rate difference not statistically significant due to small n",
        "advantages": "Superior estrus induction in low-breeding season; maintains elevated P4 during anovulatory period",
        "limitations": "Small sample size; single season study",
        "notes": "PMID: 27047075; PMC4774744"
    },

    {
        "sno": 3,
        "title": "Controlled breeding and reproductive management in water buffaloes (Bubalus bubalis) using Eazi Breed controlled internal drug release",
        "author": "Pawshe CH",
        "year": 2015,
        "journal": "Journal of the South African Veterinary Association",
        "publisher": "AOSIS Publishing",
        "country": "India",
        "institution": "Department of Animal Science, University of Agricultural Sciences, Dharwad, Karnataka",
        "animal": "Anoestrus water buffalo (Bubalus bubalis)",
        "sample": "500",
        "naas": "Not Reported",
        "impact": "0.9",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed",
        "doi": "https://doi.org/10.4102/jsava.v86i1.1064",
        "pdf": "https://jsava.co.za/index.php/jsava/article/view/1064/1432",
        "aim": "To evaluate efficiency of CIDR intravaginal progesterone device in true anoestrus buffaloes for oestrus induction and fertility under field conditions",
        "gap": "Large-scale field evaluation of CIDR in true anoestrus buffaloes under Indian tropical conditions was lacking",
        "biopolymer": "Silicone elastomer (Eazi-Breed CIDR matrix)",
        "device": "Eazi-Breed CIDR (1.38 g natural progesterone in silicone elastomer)",
        "hormones": "Progesterone (CIDR), Estradiol benzoate (Cidirol)",
        "methodology": "500 true anoestrus buffalo cows (4-6 years) from 10 villages treated with CIDR for 9 days. Cidirol (1 mg EB) administered i.m. on Day 10. AI performed at detected estrus.",
        "protocol": "Day 0 → CIDR inserted\nDay 9 → CIDR removed\nDay 10 → Estradiol benzoate (1 mg i.m.)\nDay 11-12 → AI at estrus detection",
        "timing": "AI at detected estrus 24-48 h after EB injection",
        "estrus_rate": "89.8",
        "conception": "51.11",
        "pregnancy": "Not Reported",
        "findings": "89.8% buffaloes showed estrus within 24-72 h of CIDR removal. Conception rate on first AI was 51.11%. CIDR is effective for large-scale reproductive management in anoestrus buffaloes.",
        "results": "Estrus induction: 449/500 (89.8%). Conception rate: 230/450 (51.11%) at first AI. Calving confirmed in treated animals.",
        "stats": "Descriptive statistics; large field trial with high response rates",
        "advantages": "High estrus induction rate; field-applicable; effective in true anoestrus; large-scale application feasible",
        "limitations": "No biopolymer modification; standard commercial CIDR used; no control group without treatment",
        "notes": "PMID: 26244580; Large-scale field trial in Karnataka, India"
    },
    {
        "sno": 4,
        "title": "Inclusion of CIDR in ovsynch protocol to improve fertility in postpartum subestrus buffaloes",
        "author": "Not Reported",
        "year": 2023,
        "journal": "Indian Journal of Animal Reproduction",
        "publisher": "ACS Publisher",
        "country": "India",
        "institution": "Not Reported",
        "animal": "Postpartum subestrus buffaloes",
        "sample": "24 (2 groups x 12)",
        "naas": "5.04",
        "impact": "Not Reported",
        "verification": "Peer-reviewed; NAAS listed; Indian veterinary journal",
        "doi": "https://journals.acspublisher.com/index.php/ijar/article/view/6435",
        "pdf": "PDF Not Accessible",
        "aim": "To evaluate inclusion of CIDR in Ovsynch protocol for improving fertility in postpartum subestrus buffaloes",
        "gap": "Poor fertility response to standard Ovsynch in subestrus buffaloes necessitates P4 supplementation",
        "biopolymer": "Silicone elastomer (CIDR matrix)",
        "device": "CIDR (1.38 g P4)",
        "hormones": "Progesterone (CIDR), GnRH, PGF2α",
        "methodology": "Postpartum subestrus buffaloes divided into Ovsynch (n=12) and Ovsynch+CIDR (n=12). CIDR inserted at GnRH injection and removed at PGF2α.",
        "protocol": "Day 0 → GnRH + CIDR insertion\nDay 7 → PGF2α + CIDR removal\nDay 9 → GnRH\nDay 10 → Timed AI",
        "timing": "FTAI 16-20 h after second GnRH",
        "estrus_rate": "58.33 (Ovsynch+CIDR)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Estrus detection rate was higher in Ovsynch+CIDR group (58.33%) compared to Ovsynch alone (41.66%). 25% animals exhibited premature estrus based on progesterone estimation.",
        "results": "Estrus detection: Ovsynch=41.66%, Ovsynch+CIDR=58.33%. Premature estrus observed in 25% animals.",
        "stats": "Not Reported",
        "advantages": "Improved estrus response with CIDR supplementation; prevents premature follicle luteinization",
        "limitations": "Moderate estrus rates even with CIDR; small sample size",
        "notes": "Published in Indian Journal of Animal Reproduction (IJAR)"
    },

    {
        "sno": 5,
        "title": "Enhancement of ovarian activity using certain synchronization protocols in postpartum graded Murrah buffaloes",
        "author": "Not Reported",
        "year": 2020,
        "journal": "Indian Journal of Animal Reproduction",
        "publisher": "ACS Publisher",
        "country": "India",
        "institution": "Not Reported",
        "animal": "Postpartum graded Murrah buffaloes",
        "sample": "Not Reported",
        "naas": "5.04",
        "impact": "Not Reported",
        "verification": "Peer-reviewed; NAAS listed; Indian veterinary journal",
        "doi": "https://journals.acspublisher.com/index.php/ijar/article/view/3910",
        "pdf": "PDF Not Accessible",
        "aim": "To evaluate synchronization protocols including CIDR for enhancement of ovarian activity in postpartum graded Murrah buffaloes",
        "gap": "Postpartum anovulation in buffaloes requires P4-priming to initiate cyclicity",
        "biopolymer": "Silicone elastomer (CIDR matrix)",
        "device": "CIDR (1.38 g P4)",
        "hormones": "Progesterone (CIDR), GnRH, PGF2α",
        "methodology": "Comparison of synchronization protocols including CIDR-based protocol in postpartum graded Murrah buffaloes for ovarian activity enhancement",
        "protocol": "Day 0 → CIDR insertion + GnRH\nDay 7 → PGF2α + CIDR removal\nDay 9 → GnRH\nDay 10 → FTAI",
        "timing": "FTAI 16-20 h after second GnRH injection",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "CIDR-based protocol enhanced ovarian activity and follicular development in postpartum buffaloes",
        "results": "Not Reported",
        "stats": "Not Reported",
        "advantages": "P4 priming initiates follicular waves; overcomes postpartum anovulation",
        "limitations": "Detailed outcome data not accessible from abstract",
        "notes": "Indian Journal of Animal Reproduction 41(1): 9-13"
    },
    {
        "sno": 6,
        "title": "Studies on Progesterone Concentration and Fertility Response in Postpartum Subestrus Buffaloes during Breeding and Low Breeding Seasons",
        "author": "Not Reported",
        "year": 2024,
        "journal": "Indian Journal of Animal Research",
        "publisher": "ARCC Journals",
        "country": "India",
        "institution": "Not Reported",
        "animal": "Postpartum subestrus buffaloes",
        "sample": "Not Reported",
        "naas": "5.80",
        "impact": "0.5",
        "verification": "Peer-reviewed; Scopus indexed; NAAS listed",
        "doi": "https://www.arccjournals.com/journal/indian-journal-of-animal-research/B-4702",
        "pdf": "PDF Not Accessible",
        "aim": "To study progesterone concentration and fertility response in postpartum subestrus buffaloes using P4-based protocols during different breeding seasons",
        "gap": "Seasonal variation in P4 response and fertility in subestrus buffaloes with intravaginal P4 devices",
        "biopolymer": "Silicone elastomer (CIDR/PRID matrix)",
        "device": "Intravaginal P4 device (CIDR/PRID)",
        "hormones": "Progesterone, GnRH, PGF2α",
        "methodology": "Evaluation of P4 concentration and fertility in postpartum subestrus buffaloes treated with P4-based protocols during breeding and low-breeding seasons",
        "protocol": "Not Reported",
        "timing": "Not Reported",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Seasonal effects on P4 levels and fertility response documented in subestrus buffaloes",
        "results": "Indian Journal of Animal Research 58(12): 2070-2073",
        "stats": "Not Reported",
        "advantages": "Season-specific protocol optimization possible with P4 devices",
        "limitations": "Full data not accessible from abstract",
        "notes": "Published in ARCC Journals; NAAS rated"
    },

    {
        "sno": 7,
        "title": "Effect of anti-stressor nutritional supplement in combination with progesterone implant on estrus induction and conception rate in summer anestrus Murrah buffaloes",
        "author": "Not Reported",
        "year": 2026,
        "journal": "Frontiers in Animal Science",
        "publisher": "Frontiers Media",
        "country": "India",
        "institution": "Not Reported (likely NDRI/LUVAS related)",
        "animal": "Summer anestrus Murrah buffaloes",
        "sample": "Not Reported",
        "naas": "Not Reported",
        "impact": "1.7",
        "verification": "Peer-reviewed; Scopus indexed; Open access",
        "doi": "https://www.frontiersin.org/articles/10.3389/fanim.2026.1745664",
        "pdf": "PDF Not Accessible",
        "aim": "To determine the effect of anti-stressor nutritional supplement combined with progesterone implant on estrus induction and conception rates in summer anestrus Murrah buffaloes",
        "gap": "Summer anestrus in Murrah buffaloes requires combined approach of nutritional supplementation and P4 priming",
        "biopolymer": "Silicone/polymer matrix (P4 implant)",
        "device": "Progesterone implant (intravaginal)",
        "hormones": "Progesterone (intravaginal implant)",
        "methodology": "Combination therapy: anti-stressor nutritional supplement + P4 implant in summer anestrus Murrah buffaloes. Estrus induction and conception rates evaluated.",
        "protocol": "Not Reported (recent publication 2026)",
        "timing": "Not Reported",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Combined nutritional supplementation with P4 implant improves reproductive outcomes in summer anestrus buffaloes",
        "results": "Not Reported (full text required)",
        "stats": "Not Reported",
        "advantages": "Combined approach addresses both metabolic stress and hormonal deficiency in summer anestrus",
        "limitations": "Very recent; full data pending access",
        "notes": "Frontiers in Animal Science 2026; article 1745664"
    },
    {
        "sno": 8,
        "title": "Alteration in blood biochemical profile in pregnant and non-pregnant crossbred cows following exogenous supplementation of GnRH, hCG and progesterone releasing intravaginal devices",
        "author": "Pandey NKJ",
        "year": 2016,
        "journal": "Indian Journal of Animal Reproduction",
        "publisher": "ACS Publisher",
        "country": "India",
        "institution": "College of Veterinary & Animal Sciences, GBPUAT, Pantnagar, Uttarakhand",
        "animal": "Crossbred cows (repeat breeders)",
        "sample": "18",
        "naas": "5.04",
        "impact": "Not Reported",
        "verification": "Peer-reviewed; NAAS listed",
        "doi": "https://journals.acspublisher.com/index.php/ijar/article/view/4151",
        "pdf": "PDF Not Accessible",
        "aim": "To evaluate blood biochemical alterations following GnRH, hCG, and PRID supplementation in repeat breeder crossbred cows",
        "gap": "Biochemical markers of pregnancy establishment following P4 device supplementation not well documented",
        "biopolymer": "Silicone matrix (PRID)",
        "device": "PRID (Progesterone Releasing Intravaginal Device, 1.55 g P4)",
        "hormones": "Progesterone (PRID), GnRH, hCG",
        "methodology": "Blood biochemical profiling in repeat breeder cows supplemented with GnRH (T1), hCG (T2), or PRID (T3) post-AI. Comparison of pregnant vs non-pregnant biochemical profiles.",
        "protocol": "Day 0 → AI\nDay 5 → PRID insertion (T3)\nDay 19 → PRID removal\nBlood sampling at intervals",
        "timing": "PRID Day 5-19 post-AI",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Blood biochemical parameters differed between pregnant and non-pregnant cows. PRID supplementation influenced metabolic profile.",
        "results": "Biochemical alterations documented; detailed fertility data in companion paper (Pandey et al. 2016, Vet World)",
        "stats": "Significant differences (P<0.05) in biochemical parameters",
        "advantages": "Demonstrates systemic effects of intravaginal P4 supplementation",
        "limitations": "Primarily biochemical study; reproductive outcomes reported elsewhere",
        "notes": "Companion study to Pandey et al. 2016 (Vet World)"
    },

    {
        "sno": 9,
        "title": "Comparison of follicular dynamics, superovulatory response, and embryo recovery between estradiol based and conventional superstimulation protocol in buffaloes (Bubalus bubalis)",
        "author": "Saini S",
        "year": 2015,
        "journal": "Veterinary World",
        "publisher": "Veterinary World (Open Access)",
        "country": "India",
        "institution": "ICAR-NDRI, Karnal, Haryana",
        "animal": "Murrah buffalo",
        "sample": "12",
        "naas": "6.84",
        "impact": "2.3",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; NAAS listed",
        "doi": "https://doi.org/10.14202/vetworld.2015.983-988",
        "pdf": "https://www.veterinaryworld.org/Vol.8/August-2015/19.pdf",
        "aim": "To compare estradiol-based and conventional superstimulation protocols using CIDR for follicular dynamics and embryo recovery in Murrah buffalo",
        "gap": "Need for optimized superstimulation protocols using P4 devices in buffalo for embryo transfer programs",
        "biopolymer": "Silicone elastomer (CIDR matrix)",
        "device": "CIDR (1.38 g P4)",
        "hormones": "Progesterone (CIDR), Estradiol benzoate, FSH, PGF2α, GnRH",
        "methodology": "12 Murrah buffaloes in crossover design. CIDR+EB protocol vs conventional protocol. Follicular dynamics monitored by ultrasonography. Embryo recovery on Day 6.",
        "protocol": "Day 0 → CIDR + Estradiol benzoate (2 mg)\nDay 4-7 → FSH (decreasing doses)\nDay 6 → PGF2α + CIDR removal\nDay 8 → AI (morning + evening)\nDay 14 → Embryo recovery",
        "timing": "AI 12-24 h after estrus detection",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "CIDR+EB protocol synchronized follicular wave emergence more precisely. No significant difference in embryo recovery between protocols.",
        "results": "Follicular wave emergence synchronized in CIDR+EB group. Comparable embryo recovery rates between groups.",
        "stats": "P>0.05 for embryo recovery differences between protocols",
        "advantages": "CIDR enables precise control of follicular wave for superstimulation; reusable device",
        "limitations": "Small sample; focused on superovulation rather than routine estrus synchronization",
        "notes": "PMID: 27047181; PMC4774765; NDRI Karnal study"
    },
    {
        "sno": 10,
        "title": "Clinical Management Of Repeat Breeding Cow Using Progesterone Impregnated Intravaginal Device",
        "author": "Not Reported",
        "year": "Not Reported",
        "journal": "Not Reported (Thesis/Clinical Report)",
        "publisher": "eGranth (Digital Repository of Indian Theses)",
        "country": "India",
        "institution": "Indian Veterinary Institution",
        "animal": "Repeat breeding cow",
        "sample": "Not Reported",
        "naas": "Not Reported",
        "impact": "Not Reported",
        "verification": "Indian academic repository; thesis/clinical study",
        "doi": "https://egranth.ac.in/items/0b8ea065-be31-4c6d-a587-948f74b9abd5/full",
        "pdf": "PDF Not Accessible",
        "aim": "Clinical management of repeat breeding cows using progesterone impregnated intravaginal device",
        "gap": "Field-level application of P4-impregnated intravaginal devices for repeat breeder management",
        "biopolymer": "Polymer-impregnated matrix (P4 device)",
        "device": "Progesterone impregnated intravaginal device",
        "hormones": "Progesterone (intravaginal device)",
        "methodology": "Clinical application of P4-impregnated intravaginal device in repeat breeding cows for estrus synchronization and improved conception",
        "protocol": "Not Reported",
        "timing": "Not Reported",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "P4-impregnated intravaginal device effective for clinical management of repeat breeding",
        "results": "Not Reported",
        "stats": "Not Reported",
        "advantages": "Field-applicable; non-invasive P4 delivery",
        "limitations": "Limited accessible data; thesis document",
        "notes": "Available on eGranth digital repository"
    },
]


# ============================================================
# SHEET 2: GLOBAL STUDIES
# ============================================================
global_studies = [
    {
        "sno": 1,
        "title": "Preparation of TPP-crosslinked chitosan microparticles by spray drying for the controlled delivery of progesterone intended for estrus synchronization in cattle",
        "author": "Machado ND",
        "year": 2018,
        "journal": "Pharmaceutical Research",
        "publisher": "Springer",
        "country": "Argentina",
        "institution": "CONICET, Universidad Nacional del Sur, Bahia Blanca",
        "animal": "Cattle (Angus cows - in vivo validation)",
        "sample": "6 (in vivo); formulation study",
        "naas": "Not Reported",
        "impact": "4.0",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science",
        "doi": "https://doi.org/10.1007/s11095-018-2363-z",
        "pdf": "PDF Not Accessible",
        "aim": "To develop TPP-crosslinked chitosan microparticles by spray drying for controlled intramuscular delivery of progesterone for estrus synchronization in cattle",
        "gap": "Need for biodegradable polymer-based controlled P4 delivery to replace repeated injections and intravaginal devices",
        "biopolymer": "Chitosan (TPP-crosslinked)",
        "device": "Injectable chitosan microparticles (not intravaginal sponge but biopolymer P4 delivery for estrus synchronization)",
        "hormones": "Progesterone (encapsulated in chitosan microparticles)",
        "methodology": "Chitosan microparticles prepared by spray drying with TPP crosslinking. Effect of formulation parameters studied. In vitro release at pH 4.5 and 7.4. Mathematical model for plasma P4 prediction. In vivo validation in 6 Angus cows.",
        "protocol": "Single injection of chitosan-P4 microparticles → sustained P4 release over 7+ days",
        "timing": "Designed for single-dose sustained release to synchronize estrus",
        "estrus_rate": "Not Reported (formulation study with pharmacokinetic validation)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Chitosan microparticles showed burst and diffusion-controlled release phases. P4 released faster at low pH. In vivo delivery affected by particle size and initial hormone content. Plasma P4 maintained above 1 ng/mL for extended period.",
        "results": "Sustained P4 release achieved. Mathematical model validated with in vivo data. Particle size and drug loading critical for extended release.",
        "stats": "Mathematical modeling R2 values reported; in vitro-in vivo correlation established",
        "advantages": "Biodegradable; single-dose administration; no device retention/loss issues; reduced animal handling",
        "limitations": "Injectable not intravaginal; reproductive outcome (conception) not measured; small in vivo sample",
        "notes": "PMID: 29464352; Key biopolymer P4 delivery paper for cattle"
    },
    {
        "sno": 2,
        "title": "Design and evaluation of a recyclable intravaginal device made of ethylene vinyl acetate copolymer for bovine estrus synchronization",
        "author": "Florencia A",
        "year": 2020,
        "journal": "Drug Delivery and Translational Research",
        "publisher": "Springer",
        "country": "Argentina",
        "institution": "CONICET, PLAPIQUI, Universidad Nacional del Sur",
        "animal": "Bovine (Angus heifers)",
        "sample": "60",
        "naas": "Not Reported",
        "impact": "3.8",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science",
        "doi": "https://doi.org/10.1007/s13346-020-00717-4",
        "pdf": "PDF Not Accessible",
        "aim": "To design and evaluate a recyclable intravaginal device made of EVA copolymer for bovine estrus synchronization that can be reused unlike silicone devices",
        "gap": "Current silicone CIDR devices cannot be recycled/reused after single use; EVA-based devices may allow multiple uses",
        "biopolymer": "Ethylene Vinyl Acetate (EVA) copolymer",
        "device": "EVA-based intravaginal device (P4 loaded)",
        "hormones": "Progesterone (in EVA matrix), Estradiol benzoate, PGF2α, GnRH",
        "methodology": "EVA devices manufactured by injection molding with P4. In vitro release studies. In vivo trial: 60 Angus heifers randomized to EVA device vs commercial silicone CIDR. Plasma P4 monitored. Estrus response evaluated.",
        "protocol": "Day 0 → EVA-P4 device inserted + EB (2 mg i.m.)\nDay 7 → PGF2α + device removal\nDay 8 → GnRH\nDay 9 → Fixed-time AI",
        "timing": "FTAI 52-56 h after device removal",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "52 (EVA group comparable to commercial CIDR)",
        "findings": "EVA intravaginal devices maintained plasma P4 above 2 ng/mL similar to commercial silicone CIDR. Pregnancy rates comparable between EVA and commercial devices. EVA device recyclable.",
        "results": "Pregnancy rate: EVA device comparable to commercial CIDR (~52%). Plasma P4 profiles overlapping between treatments. Device retained in all animals.",
        "stats": "P>0.05 for pregnancy rate difference (non-inferiority demonstrated)",
        "advantages": "Recyclable; cost-effective; biocompatible; comparable efficacy to commercial CIDR; reduced environmental waste",
        "limitations": "EVA is synthetic copolymer not natural biopolymer; limited to heifers",
        "notes": "Key paper demonstrating polymer-based alternative to silicone for intravaginal P4 delivery in cattle"
    },

    {
        "sno": 3,
        "title": "Development of an injection molded ethylene-vinyl acetate copolymer (EVA) intravaginal insert for the delivery of progesterone to cattle",
        "author": "Rathbone MJ",
        "year": 2015,
        "journal": "Journal of Controlled Release",
        "publisher": "Elsevier",
        "country": "New Zealand",
        "institution": "InterAg, Hamilton, New Zealand",
        "animal": "Dairy cattle",
        "sample": "Not Reported",
        "naas": "Not Reported",
        "impact": "11.5",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science; High impact",
        "doi": "https://doi.org/10.1016/j.jconrel.2015.05.275",
        "pdf": "PDF Not Accessible",
        "aim": "To develop a new injection-molded EVA intravaginal insert for P4 delivery to cattle for 7-day insertion period with reduced residual drug",
        "gap": "Silicone-based devices retain large residual P4 after use; EVA-based manufacturing can reduce waste and improve release efficiency",
        "biopolymer": "Ethylene Vinyl Acetate (EVA) copolymer",
        "device": "Injection-molded EVA intravaginal insert (P4-loaded)",
        "hormones": "Progesterone (in EVA matrix)",
        "methodology": "Injection molding of EVA with P4. Comparison of P4 release kinetics and residual drug content vs commercial silicone CIDR. In vivo plasma P4 profile measurement in cattle.",
        "protocol": "Day 0 → EVA-P4 insert placed\nDay 7 → Insert removed\nPlasma P4 monitored daily",
        "timing": "7-day device retention period",
        "estrus_rate": "Not Reported (device development study)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "EVA manufacturing reduced residual drug vs silicone insert while maintaining biological performance. P4 plasma levels maintained above 2 ng/mL throughout insertion period.",
        "results": "Reduced residual P4 in EVA device vs silicone CIDR. Bioequivalent plasma P4 profiles. Successful 7-day P4 delivery.",
        "stats": "Pharmacokinetic comparison; P4 AUC values comparable",
        "advantages": "Reduced drug waste; injection molding scalable; bioequivalent P4 delivery; cost-effective manufacturing",
        "limitations": "Device development focus; reproductive outcomes not primary endpoint",
        "notes": "PMID: 26022232; Foundational paper for EVA-based intravaginal P4 technology"
    },
    {
        "sno": 4,
        "title": "Development of an injection molded poly(epsilon-caprolactone) intravaginal insert for the delivery of progesterone to cattle",
        "author": "Rathbone MJ",
        "year": 2002,
        "journal": "Journal of Controlled Release",
        "publisher": "Elsevier",
        "country": "New Zealand",
        "institution": "InterAg, Hamilton; University of Otago, Dunedin",
        "animal": "Dairy cattle (cows)",
        "sample": "Not Reported",
        "naas": "Not Reported",
        "impact": "11.5",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science; High impact",
        "doi": "https://pubmed.ncbi.nlm.nih.gov/12480312/",
        "pdf": "PDF Not Accessible",
        "aim": "To engineer poly(epsilon-caprolactone) (PCL) into a well-retained intravaginal insert for controlled P4 delivery via vagina of cows",
        "gap": "Need for biodegradable polymer alternatives to silicone for intravaginal P4 delivery in cattle",
        "biopolymer": "Poly(epsilon-caprolactone) (PCL) - biodegradable polyester",
        "device": "PCL intravaginal insert (injection molded)",
        "hormones": "Progesterone (in PCL matrix)",
        "methodology": "PCL intravaginal inserts manufactured by injection molding. Shape optimized for retention. In vitro P4 release. In vivo evaluation in cattle for device retention and P4 plasma levels.",
        "protocol": "Day 0 → PCL-P4 insert placed intravaginally\nDay 7-14 → Monitoring P4 levels\nDevice removal at end of treatment",
        "timing": "7-14 day insertion period evaluated",
        "estrus_rate": "Not Reported (device development study)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "PCL can be engineered into a well-retained intravaginal shape for controlled P4 delivery in cows. Biodegradable platform demonstrated.",
        "results": "Successful device retention. Controlled P4 release demonstrated. PCL device feasible as biodegradable alternative.",
        "stats": "In vitro release kinetics characterized",
        "advantages": "Biodegradable; no device retrieval needed potentially; environmentally friendly; controlled release achievable",
        "limitations": "Early-stage development; no reproductive outcome data; P4 levels may be suboptimal vs commercial CIDR",
        "notes": "PMID: 12480312; Pioneering paper for biodegradable polymer intravaginal P4 delivery in cattle"
    },

    {
        "sno": 5,
        "title": "Development of Vaginal Carriers Based on Chitosan-Grafted-PNIPAAm for Progesterone Administration",
        "author": "Afloarea OT",
        "year": 2022,
        "journal": "Gels",
        "publisher": "MDPI",
        "country": "Romania",
        "institution": "Grigore T. Popa University of Medicine and Pharmacy, Iasi",
        "animal": "Not specified (vaginal delivery formulation study)",
        "sample": "In vitro study",
        "naas": "Not Reported",
        "impact": "4.0",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Open Access",
        "doi": "https://doi.org/10.3390/gels8090596",
        "pdf": "https://www.mdpi.com/2310-2861/8/9/596/pdf",
        "aim": "To develop chitosan-grafted-PNIPAAm vaginal carriers for controlled progesterone administration",
        "gap": "Need for thermoresponsive biopolymer-based vaginal P4 carriers that gel in situ at body temperature",
        "biopolymer": "Chitosan-grafted-poly(N-isopropylacrylamide) (Chitosan-g-PNIPAAm)",
        "device": "Thermoresponsive vaginal gel/carrier (in situ gelling at body temperature)",
        "hormones": "Progesterone",
        "methodology": "Synthesis of chitosan-g-PNIPAAm copolymers. Characterization by FTIR, NMR, DSC. Lower critical solution temperature (LCST) determination. P4 loading and in vitro release studies in simulated vaginal fluid.",
        "protocol": "In vitro: P4-loaded chitosan-PNIPAAm gel transitions at 32-37°C → sustained P4 release in vaginal conditions",
        "timing": "Sustained release over 24-72 h designed",
        "estrus_rate": "Not Reported (in vitro formulation study)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Chitosan-g-PNIPAAm showed thermoresponsive behavior with LCST near body temperature. P4 incorporated successfully. Sustained release achieved in simulated vaginal fluid.",
        "results": "Thermoresponsive gelling at body temperature confirmed. P4 release sustained over multiple days. Mucoadhesive properties enhanced by chitosan.",
        "stats": "In vitro release kinetics; Higuchi model fitting",
        "advantages": "Biodegradable; thermoresponsive (liquid→gel at body temp); mucoadhesive; no device retrieval needed; sustained release",
        "limitations": "In vitro only; no animal trials; no estrus synchronization data",
        "notes": "PMC9498816; Highly relevant biopolymer P4 vaginal delivery system"
    },
    {
        "sno": 6,
        "title": "In Vitro and Ex Vivo Evaluation of Novel Methacrylated Chitosan-PNIPAAm-Hyaluronic Acid Hydrogels Loaded with Progesterone for Applications in Vaginal Delivery",
        "author": "Afloarea OT",
        "year": 2024,
        "journal": "Polymers",
        "publisher": "MDPI",
        "country": "Romania",
        "institution": "Grigore T. Popa University of Medicine and Pharmacy, Iasi",
        "animal": "Ex vivo (vaginal tissue)",
        "sample": "In vitro/ex vivo",
        "naas": "Not Reported",
        "impact": "5.0",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science; Open Access",
        "doi": "https://doi.org/10.3390/polym16152160",
        "pdf": "https://www.mdpi.com/2073-4360/16/15/2160/pdf",
        "aim": "To evaluate methacrylated chitosan-PNIPAAm-hyaluronic acid hydrogels loaded with P4 for vaginal delivery applications",
        "gap": "Need for advanced biopolymer hydrogels combining mucoadhesion, thermoresponsiveness, and sustained P4 release for intravaginal applications",
        "biopolymer": "Methacrylated Chitosan + PNIPAAm + Hyaluronic Acid (triple biopolymer hydrogel)",
        "device": "Hydrogel-based vaginal delivery system",
        "hormones": "Progesterone",
        "methodology": "Synthesis of methacrylated chitosan-PNIPAAm-HA hydrogels. P4 loading. In vitro release in SVF. Ex vivo permeation through vaginal tissue. Cytotoxicity assessment.",
        "protocol": "In vitro/ex vivo: P4-loaded hydrogel → sustained release through vaginal tissue at 37°C",
        "timing": "Sustained release over 24-96 h demonstrated",
        "estrus_rate": "Not Reported (formulation/ex vivo study)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Triple-component hydrogel showed excellent P4 loading, sustained release, good mucoadhesion, and biocompatibility. Ex vivo permeation confirmed P4 transport through vaginal tissue.",
        "results": "Sustained P4 release over 96 h. Non-cytotoxic to vaginal cells. Enhanced mucoadhesion vs single-polymer systems.",
        "stats": "Release kinetics; permeation coefficients; cell viability >85%",
        "advantages": "Triple biopolymer synergy; biodegradable; thermoresponsive; mucoadhesive; biocompatible; no device needed",
        "limitations": "No in vivo animal trial; human-oriented but applicable to veterinary use",
        "notes": "PMC11313938; Advanced biopolymer P4 vaginal delivery - highly relevant to veterinary applications"
    },

    {
        "sno": 7,
        "title": "The potential of biodegradable polymers: Chitosan, polyethylene glycol, and polycaprolactone as materials for progesterone intravaginal devices",
        "author": "Not Reported",
        "year": 2024,
        "journal": "Livestock and Animal Research",
        "publisher": "Universitas Sebelas Maret (UNS), Indonesia",
        "country": "Indonesia",
        "institution": "Universitas Sebelas Maret",
        "animal": "Cattle (bovine vaginal tissue evaluation)",
        "sample": "In vitro/in vivo degradation study",
        "naas": "Not Reported",
        "impact": "Not Reported",
        "verification": "Peer-reviewed; Open access journal",
        "doi": "https://jurnal.uns.ac.id/lar/article/view/72985",
        "pdf": "PDF Not Accessible",
        "aim": "To evaluate potential of biodegradable polymers (chitosan, PEG, PCL) as materials for progesterone intravaginal devices in cattle",
        "gap": "Limited data on combined biodegradable polymer systems (chitosan-PEG-PCL) for intravaginal P4 devices in cattle",
        "biopolymer": "Chitosan + Polyethylene Glycol (PEG) + Polycaprolactone (PCL) combination",
        "device": "Chitosan-PEG-PCL intravaginal implant",
        "hormones": "Progesterone",
        "methodology": "Melting and molding process for PCL-PEG-chitosan implants. Degradation in simulated vaginal fluid and bovine vaginal tissue. P4 release kinetics. Chitosan-PEG formulation released P4 for 4 days.",
        "protocol": "Implant insertion → degradation in vaginal environment → P4 release over 4 days (chitosan-PEG) or longer (PCL-containing)",
        "timing": "4-7 days sustained release depending on formulation",
        "estrus_rate": "Not Reported (material science study)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Chitosan-PEG implant released P4 for 4 days corresponding to implant degradation time in vagina. PCL-PEG-chitosan combination showed tunable degradation in simulated vaginal fluid and bovine vaginal tissue.",
        "results": "P4 release duration: 4 days (chitosan-PEG); longer with PCL. Device degraded in vaginal environment. Tunable release achievable.",
        "stats": "Release kinetics characterized; degradation profiles documented",
        "advantages": "Fully biodegradable (no retrieval needed); tunable release duration; biocompatible; cost-effective natural polymers",
        "limitations": "No in vivo reproductive outcome data; device optimization ongoing",
        "notes": "Directly relevant to intravaginal biopolymer P4 device development for cattle"
    },
    {
        "sno": 8,
        "title": "Long lasting mucoadhesive membrane based on alginate and chitosan for intravaginal drug delivery",
        "author": "Saporito F",
        "year": 2020,
        "journal": "Journal of Materials Science: Materials in Medicine",
        "publisher": "Springer",
        "country": "Italy",
        "institution": "University of Pavia, Italy",
        "animal": "In vitro (vaginal delivery system)",
        "sample": "In vitro formulation study",
        "naas": "Not Reported",
        "impact": "4.2",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science",
        "doi": "https://doi.org/10.1007/s10856-020-6359-y",
        "pdf": "PDF Not Accessible",
        "aim": "To develop long-lasting mucoadhesive membrane based on alginate and chitosan for controlled intravaginal drug delivery",
        "gap": "Need for stable, mucoadhesive intravaginal membranes using natural biopolymers for sustained drug release",
        "biopolymer": "Alginate + Chitosan (polyelectrolyte complex membrane)",
        "device": "Mucoadhesive intravaginal membrane",
        "hormones": "Model drug (platform applicable to P4 delivery)",
        "methodology": "Alginate-chitosan membrane fabrication by polyelectrolyte complexation. Stability in simulated vaginal fluid. Mucoadhesion testing. Drug release kinetics.",
        "protocol": "Membrane fabrication → placement in vaginal environment → sustained drug release via mucoadhesion",
        "timing": "Extended release over days demonstrated",
        "estrus_rate": "Not Reported (drug delivery platform study)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Alginate-chitosan membrane stable in simulated vaginal environment. Easy to fabricate. Controlled release of model drug achieved. Mucoadhesive properties confirmed.",
        "results": "Stable membrane in vaginal pH. Sustained release confirmed. Strong mucoadhesion to vaginal tissue.",
        "stats": "Mucoadhesion force measurements; release kinetics (Korsmeyer-Peppas model)",
        "advantages": "Natural biopolymers; mucoadhesive (no physical retention device needed); biodegradable; scalable fabrication",
        "limitations": "P4 not specifically tested (model drug used); no animal trials; human medicine focused",
        "notes": "Platform technology directly transferable to intravaginal P4 delivery for livestock"
    },

    {
        "sno": 9,
        "title": "Progesterone-releasing devices for cattle estrus induction and synchronization: Device optimization to anticipate shorter treatment durations and new device developments",
        "author": "Martinez-Ros P",
        "year": 2018,
        "journal": "Theriogenology",
        "publisher": "Elsevier",
        "country": "Spain",
        "institution": "Universidad CEU Cardenal Herrera, Valencia",
        "animal": "Cattle (review of multiple species/breeds)",
        "sample": "Review article",
        "naas": "Not Reported",
        "impact": "2.8",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science",
        "doi": "https://doi.org/10.1016/j.theriogenology.2017.10.009",
        "pdf": "PDF Not Accessible",
        "aim": "To review P4-releasing devices for cattle estrus induction/synchronization with focus on device optimization for shorter treatments and new polymer-based developments",
        "gap": "Comprehensive review of evolving P4 device technology including new polymeric materials for intravaginal delivery in cattle",
        "biopolymer": "Review: Silicone, EVA, PCL, and emerging polymers discussed",
        "device": "CIDR, PRID, DIB, Cue-Mate, and new polymer devices (EVA, PCL-based)",
        "hormones": "Progesterone (various devices), GnRH, PGF2α, Estradiol",
        "methodology": "Systematic review of P4-releasing intravaginal devices. Discussion of silicone, EVA, and biodegradable polymer (PCL) devices. Assessment of short-duration protocols.",
        "protocol": "Review covers multiple protocols:\nStandard: Day 0 → Device in; Day 7-9 → Device out + PGF2α; Day 8-10 → AI\nShort: Day 0 → Device in; Day 5 → Device out + PGF2α; Day 6-7 → AI",
        "timing": "Standard 7-9 day and short 5-day protocols reviewed",
        "estrus_rate": "Variable: 70-100% across studies reviewed",
        "conception": "Variable: 35-55% across studies reviewed",
        "pregnancy": "Variable: 30-52% across studies reviewed",
        "findings": "Short 5-day CIDR protocols effective with adequate P4 supplementation. EVA and PCL devices show promise as alternatives. New device technologies reduce residual drug waste.",
        "results": "Review: 5-day protocols viable; EVA devices bioequivalent to silicone; PCL biodegradable devices feasible; P4 release profile critical for outcomes",
        "stats": "Meta-analysis of multiple studies; varied significance levels",
        "advantages": "Reviews full spectrum of P4 device technology including biodegradable options; short protocols reduce cost and handling",
        "limitations": "Review article; no primary experimental data",
        "notes": "PMID: 29033104; Comprehensive review of device materials including biopolymers"
    },
    {
        "sno": 10,
        "title": "Intravaginal administration of progesterone using a new technique for sustained drug release in goats",
        "author": "Romano JE",
        "year": 2000,
        "journal": "Small Ruminant Research",
        "publisher": "Elsevier",
        "country": "Uruguay/USA",
        "institution": "Universidad de la Republica, Montevideo",
        "animal": "Goats",
        "sample": "20",
        "naas": "Not Reported",
        "impact": "1.8",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science",
        "doi": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7593637/",
        "pdf": "PDF Not Accessible",
        "aim": "To evaluate a novel biopolymer-based technique (gelatin capsule with silicone fluid) for sustained intravaginal P4 release in goats",
        "gap": "Need for simple, low-cost intravaginal P4 delivery using biopolymer carriers in small ruminants",
        "biopolymer": "Gelatin capsule + Hydroxypropylmethylcellulose (HPMC) or Polyacryl starch (PA)",
        "device": "Gelatin capsule containing 0.4 g P4 mixed in silicone fluid with HPMC or PA base (intravaginal placement)",
        "hormones": "Progesterone (0.4 g in gelatin-biopolymer capsule)",
        "methodology": "Goats administered gelatin capsule containing P4 (0.4 g) mixed with silicone fluid and either HPMC or PA base intravaginally. Plasma P4 monitored. Estrus response evaluated post-removal.",
        "protocol": "Day 0 → Gelatin-P4 capsule inserted intravaginally\nDay 6-14 → Capsule provides sustained P4 release\nDay 14 → Capsule degraded/removed\nEstrus monitoring post-treatment",
        "timing": "P4 sustained for capsule duration; estrus post-treatment",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Gelatin capsule with HPMC or PA base provided sustained P4 release intravaginally. P4 plasma levels elevated during treatment. Novel biopolymer carrier concept demonstrated.",
        "results": "Sustained intravaginal P4 release via biopolymer capsule feasible in goats. HPMC and PA bases showed different release characteristics.",
        "stats": "Plasma P4 levels significantly elevated vs baseline during treatment",
        "advantages": "Biodegradable (gelatin); low-cost; simple fabrication; cellulose/starch bases are natural polymers",
        "limitations": "Goats (not dairy cattle/buffalo); small sample; early concept",
        "notes": "PMC7593637; Foundational paper for biopolymer intravaginal P4 delivery"
    },

    {
        "sno": 11,
        "title": "The effect of addition of equine chorionic gonadotropin to a progesterone-based estrous synchronization protocol in buffaloes (Bubalus bubalis) under tropical conditions",
        "author": "de Araujo Berber RC",
        "year": 2009,
        "journal": "Tropical Animal Health and Production",
        "publisher": "Springer",
        "country": "Brazil",
        "institution": "Universidade Federal de Mato Grosso, Cuiaba",
        "animal": "Buffaloes (Bubalus bubalis)",
        "sample": "56",
        "naas": "Not Reported",
        "impact": "2.2",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed; Web of Science",
        "doi": "https://doi.org/10.1007/s11250-008-9281-x",
        "pdf": "PDF Not Accessible",
        "aim": "To evaluate effect of eCG addition to CIDR-based estrous synchronization protocol in buffalo under tropical conditions",
        "gap": "Optimizing CIDR-based protocols in buffalo with eCG supplementation for improved follicular growth in tropical environments",
        "biopolymer": "Silicone elastomer (CIDR matrix)",
        "device": "CIDR (1.38 g P4)",
        "hormones": "Progesterone (CIDR), GnRH, PGF2α, eCG (500 IU)",
        "methodology": "56 buffaloes divided into CIDR (n=27) and CIDR+eCG (n=29) groups. CIDR for 8 days. GnRH Day 0, PGF2α Day 7, eCG at PGF2α (CIDR+eCG group), GnRH Day 9, FTAI Day 10.",
        "protocol": "Day 0 → GnRH + CIDR insertion\nDay 7 → PGF2α + CIDR removal (± eCG 500 IU)\nDay 9 → GnRH\nDay 10 → Fixed-time AI",
        "timing": "FTAI 16 h after second GnRH (Day 10)",
        "estrus_rate": "Not Reported",
        "conception": "Not Reported",
        "pregnancy": "35 (CIDR+eCG) vs 20 (CIDR alone)",
        "findings": "Addition of eCG at CIDR removal improved ovulation rate and pregnancy rate in buffalo. Larger dominant follicle at FTAI in eCG group.",
        "results": "Pregnancy rate: CIDR+eCG=35%, CIDR alone=20%. Ovulation rate higher in eCG group. Follicle diameter at FTAI larger in eCG group.",
        "stats": "P<0.05 for follicle diameter; pregnancy rate difference approached significance",
        "advantages": "eCG supplementation improves CIDR protocol outcomes in buffalo; applicable to tropical conditions",
        "limitations": "Moderate pregnancy rates overall; buffalo-specific challenges",
        "notes": "PMID: 19181376; Important CIDR-buffalo study from Brazil"
    },
    {
        "sno": 12,
        "title": "Chitosan-alginate mucoadhesive vaginal tablets: in vitro evaluation and pharmacokinetics/pharmacodynamics in female rabbits",
        "author": "Jelvehgari M",
        "year": 2017,
        "journal": "Drug Delivery and Translational Research",
        "publisher": "Springer",
        "country": "Iran",
        "institution": "Tabriz University of Medical Sciences, Iran",
        "animal": "Female rabbits (pharmacokinetic model)",
        "sample": "In vitro + in vivo rabbits",
        "naas": "Not Reported",
        "impact": "3.8",
        "verification": "Peer-reviewed; Scopus indexed; PubMed indexed",
        "doi": "https://pubmed.ncbi.nlm.nih.gov/28956650/",
        "pdf": "PDF Not Accessible",
        "aim": "To develop and evaluate chitosan-alginate mucoadhesive vaginal tablets for progesterone delivery with enhanced bioavailability",
        "gap": "Oral P4 has low bioavailability; vaginal chitosan-alginate tablets can provide sustained local and systemic P4 delivery",
        "biopolymer": "Chitosan + Alginate (mucoadhesive tablet matrix)",
        "device": "Chitosan-alginate mucoadhesive vaginal tablet (P4-loaded)",
        "hormones": "Progesterone",
        "methodology": "Chitosan-alginate vaginal tablets prepared by direct compression. In vitro P4 release. In vivo pharmacokinetics in female rabbits. Comparison with oral P4.",
        "protocol": "Vaginal tablet insertion → sustained P4 release → blood sampling for pharmacokinetics",
        "timing": "Sustained release over 24+ hours demonstrated",
        "estrus_rate": "Not Reported (pharmacokinetic study)",
        "conception": "Not Reported",
        "pregnancy": "Not Reported",
        "findings": "Chitosan-alginate vaginal tablets showed 2-fold higher mean residence time (MRT) and 5-fold higher bioavailability compared to oral P4 in rabbits.",
        "results": "MRT: 2x higher vs oral P4. Bioavailability: 5x higher vs oral P4. Sustained release from vaginal tablet confirmed.",
        "stats": "Pharmacokinetic parameters: Cmax, Tmax, AUC, MRT all significantly different from oral (P<0.05)",
        "advantages": "Natural biopolymers; mucoadhesive; 5x better bioavailability than oral; sustained release; simple tablet formulation",
        "limitations": "Rabbit model (not cattle/buffalo); tablet form may differ from sponge/device",
        "notes": "PMID: 28956650; Demonstrates biopolymer vaginal P4 delivery superiority"
    },
]


# ============================================================
# EXCEL WORKBOOK GENERATION
# ============================================================

def format_sheet(ws, data, sheet_title):
    """Format a worksheet with headers, data, and styling."""
    ws.title = sheet_title
    
    # Style definitions
    header_font = Font(bold=True, size=11, color="FFFFFF")
    header_fill = PatternFill(start_color="2F5496", end_color="2F5496", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    
    data_alignment = Alignment(vertical="top", wrap_text=True)
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    even_fill = PatternFill(start_color="D6E4F0", end_color="D6E4F0", fill_type="solid")
    odd_fill = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")
    
    # Write headers
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border
    
    # Write data
    keys = [
        "sno", "title", "author", "year", "journal", "publisher", "country",
        "institution", "animal", "sample", "naas", "impact", "verification",
        "doi", "pdf", "aim", "gap", "biopolymer", "device", "hormones",
        "methodology", "protocol", "timing", "estrus_rate", "conception",
        "pregnancy", "findings", "results", "stats", "advantages",
        "limitations", "notes"
    ]
    
    for row_idx, study in enumerate(data, 2):
        row_fill = even_fill if row_idx % 2 == 0 else odd_fill
        for col_idx, key in enumerate(keys, 1):
            value = study.get(key, "Not Reported")
            cell = ws.cell(row=row_idx, column=col_idx, value=str(value))
            cell.alignment = data_alignment
            cell.border = thin_border
            cell.fill = row_fill
    
    # Set column widths
    col_widths = {
        1: 8, 2: 45, 3: 18, 4: 8, 5: 30, 6: 20, 7: 12, 8: 40,
        9: 25, 10: 15, 11: 10, 12: 10, 13: 35, 14: 45, 15: 35,
        16: 50, 17: 45, 18: 30, 19: 35, 20: 30, 21: 55, 22: 50,
        23: 35, 24: 15, 25: 15, 26: 15, 27: 55, 28: 55, 29: 35,
        30: 50, 31: 40, 32: 40
    }
    
    for col, width in col_widths.items():
        ws.column_dimensions[get_column_letter(col)].width = width
    
    # Freeze top row
    ws.freeze_panes = "A2"
    
    # Enable auto-filter
    ws.auto_filter.ref = ws.dimensions


# Create Sheet 1: India Studies
ws1 = wb.active
format_sheet(ws1, india_studies, "INDIA STUDIES")

# Create Sheet 2: Global Studies
ws2 = wb.create_sheet()
format_sheet(ws2, global_studies, "GLOBAL STUDIES")

# Save workbook
output_path = "/projects/sandbox/MAIN-KIRO/Biopolymer_P4_Intravaginal_Sponge_Studies.xlsx"
wb.save(output_path)
print(f"Excel workbook saved to: {output_path}")
print(f"Sheet 1: INDIA STUDIES - {len(india_studies)} studies")
print(f"Sheet 2: GLOBAL STUDIES - {len(global_studies)} studies")
